### ISSUE TITLE
Request for COMP5511 Quiz 2 Materials

### ISSUE THREAD

**Issue by Andy-king6** [jerrykhh/polyu#1]
Dear Senior Jerrykhh, I was wondering if you could kindly upload the materials for Quiz 2 of the COMP5511 course. I believe it would be of great help to me and other students who are also studying this course.Thank you!

**Comment by jerrykhh** [comment]
Hi Andy,

Sorry about that. In my study, the COMP5511 do not have quiz 2 so I cannot share it. You can share it after the quiz 2 if you can. Thanks.

Best Regards,
Jerry

**Comment by Andy-king6** [comment]
Thanks for your reply, that's fine.
